Лабораторная работа 5 «Метрики качества классификации»
Шаймарданов Руслан,группа Р4117
Датасет: http://archive.ics.uci.edu/ml/datasets/Statlog+%28Shuttle%29
Количество записей: 14500
Описание:
The shuttle dataset contains 9 attributes all of which are numerical. The first one being time. The last column is the class which has been coded as follows:
1   Rad Flow
2   Fpv Close
3   Fpv Open
4   High
5   Bypass
6   Bpv Close
7   Bpv Open

Подключение библиотек

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import pylab as pl
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc, confusion_matrix, classification_report

Подготовка данных

In [2]:
dataset = pd.read_csv("shuttle.csv", header=None).values.astype(np.int32, copy=False)
x = dataset[:,:-1]
y = dataset[:,-1]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=7)
svc = svm.SVC(kernel='rbf', probability=True)
lr = LogisticRegression()

a. Classification Accuracy

In [3]:
scoring='accuracy'
print("Accuracy:")
results = cross_val_score(lr, x, y, scoring=scoring)
print("Logistic Regression: %.4f (%.4f)" % (results.mean(), results.std()))
results = cross_val_score(svc, x, y, scoring=scoring)
print("Support Vector Machine: %.4f (%.4f)" % (results.mean(), results.std()))

Accuracy:
Logistic Regression: 0.9254 (0.0029)
Support Vector Machine: 0.9306 (0.0020)


b. Logarithmic Loss

In [4]:
scoring='neg_log_loss'
print("Logloss:")
results = cross_val_score(lr, x, y, scoring=scoring)
print("Logistic Regression: %.4f (%.4f)" % (results.mean(), results.std()))
results = cross_val_score(svc, x, y, scoring=scoring)
print("Support Vector Machine: %.4f (%.4f)" % (results.mean(), results.std()))

Logloss:
Logistic Regression: -0.2622 (0.0135)
Support Vector Machine: -0.0530 (0.0035)


c. Area Under ROC Curve

In [5]:
scoring='roc_auc'
print("AUC:")
yb = list(map(lambda x: int(x==1), y))
results = cross_val_score(lr, x, yb, scoring=scoring)
print("Logistic Regression: %.4f (%.4f)" % (results.mean(), results.std()))
results = cross_val_score(svc, x, yb, scoring=scoring)
print("Support Vector Machine: %.4f (%.4f)" % (results.mean(), results.std()))

AUC:
Logistic Regression: 0.9719 (0.0276)
Support Vector Machine: 0.9999 (0.0000)


d. Confusion Matrix

In [6]:
print("Confusion Matrix:")
lr.fit(x_train, y_train)
predicted = lr.predict(x_test)
matrix = confusion_matrix(y_test, predicted)
print("Logistic Regression:\n", matrix)
svc.fit(x_train, y_train)
predicted = svc.predict(x_test)
matrix = confusion_matrix(y_test, predicted)
print("Support Vector Machine:\n", matrix)

Confusion Matrix:
Logistic Regression:
 [[3754    0    0   10    0    0    1]
 [   2    0    0    2    0    0    0]
 [   3    0    0   12    0    1    0]
 [ 310    0    0  412    0    0    0]
 [   0    0    0    0  275    0    0]
 [   2    0    0    1    0    0    0]
 [   0    0    0    0    0    0    0]]
Support Vector Machine:
 [[3765    0    0    0    0    0]
 [   3    1    0    0    0    0]
 [  15    0    1    0    0    0]
 [ 178    0    0  544    0    0]
 [ 121    0    0    0  154    0]
 [   3    0    0    0    0    0]]


e. Classification Report

Вывод:
В ходе лабораторной работы были рассмотрены 5 различных метрик качества классификации.

Метод оценки с ROC-кривой является оценкой бинарного классификатора, поэтому для сравнения данные были приведены к двум классам: первый, составлющий 80% от всех, и все остальные.

Для выполнения работы были выбраны методы: Support Vector Machine (как последний из изученных) и Logistic Regression (для знакомства с чем-то новым). Метод опорных векторов показал чуть лучшие результаты.